version: '3.8'

services:
  binance-mcp-server:
    build: .
    container_name: binance-mcp-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - BINANCE_TESTNET=${BINANCE_TESTNET:-true}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-binance-mcp-server}
      - MCP_SERVER_VERSION=${MCP_SERVER_VERSION:-1.0.0}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./logs:/app/logs
    # ports:
    #   - "3000:3000"  # 如果 MCP server 需要暴露端口，取消注释此行
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M